# Generated by Django 3.2.7 on 2021-09-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210923_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purchased_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
