# Generated by Django 3.2.7 on 2021-09-27 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_purchased_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='payment/screenshots/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
