# Generated by Django 3.2.7 on 2021-09-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20210927_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment/screenshots/'),
        ),
    ]
