# Generated by Django 3.2.7 on 2021-09-25 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20210923_1835'),
        ('qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodegenerator',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode', to='ticket.ticket'),
        ),
    ]
