# Generated by Django 3.2.7 on 2021-09-25 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20210923_1835'),
        ('qrcode', '0002_alter_qrcodegenerator_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodegenerator',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_qrcode', to='ticket.ticket'),
        ),
    ]
