# Generated by Django 3.2.7 on 2021-09-27 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0003_alter_qrcodegenerator_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodegenerator',
            name='qrcode',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='qrcodegenerator',
            name='qrimage',
            field=models.ImageField(null=True, upload_to='QRcode/'),
        ),
        migrations.AlterField(
            model_name='qrcodegenerator',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
