# Generated by Django 3.2.7 on 2021-09-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0004_auto_20210927_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodegenerator',
            name='qrimage',
            field=models.ImageField(blank=True, null=True, upload_to='QRcode/'),
        ),
    ]
