# Generated by Django 3.2.7 on 2021-10-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0005_alter_qrcodegenerator_qrimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodegenerator',
            name='qrimage',
        ),
        migrations.AlterField(
            model_name='qrcodegenerator',
            name='qrcode',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
