# Generated by Django 3.2.7 on 2021-10-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eid',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
