# Generated by Django 3.2.7 on 2021-09-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_ticket_purchased_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='purchased_at',
        ),
    ]
