# Generated by Django 3.2.7 on 2021-09-23 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0004_remove_ticket_purchased_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlogs',
            name='status_recorded',
            field=models.CharField(choices=[('P', 'Pass'), ('E', 'Expire'), ('I', 'Issue'), ('N', 'Null')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='scanlogs',
            name='scanned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_scan_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scanlogs',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='ticket.ticket'),
        ),
    ]
