# Generated by Django 3.2.7 on 2021-09-27 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20210923_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='discripton',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
