# Generated by Django 3.2.7 on 2021-10-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_validity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='extral_info',
        ),
        migrations.AddField(
            model_name='ticket',
            name='table',
            field=models.IntegerField(null=True),
        ),
    ]
