# Generated by Django 3.2.7 on 2021-10-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20211001_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qrcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
