# Generated by Django 3.2.9 on 2021-12-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_ticket_issend'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
