# Generated by Django 3.2.9 on 2021-12-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='table',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
