# Generated by Django 3.2.9 on 2022-07-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_alter_ticket_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['isSend', 'number'], 'permissions': [('change_validity_status', 'Can change the validity status of ticket'), ('change_checked_status', 'Can change the check status of the ticket')]},
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
