# Generated by Django 3.2.9 on 2022-07-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_securitylayer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securitylayer',
            options={'ordering': ['layer']},
        ),
        migrations.RenameField(
            model_name='securitylayer',
            old_name='order',
            new_name='layer',
        ),
    ]
