# Generated by Django 3.2.9 on 2022-07-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_auto_20220723_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylayer',
            name='layer',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
