# Generated by Django 3.2.9 on 2022-07-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_alter_securitylayer_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylayer',
            name='layer',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
    ]
